"""Deterministic, RNG-free, short-horizon local obstacle-navigation layer.

Policy-independent: this module knows nothing about pursuit, weaving,
evasion, or any other hostile-specific (or defender-specific) guidance
logic. It receives a single "base command" direction (whatever the caller
would have flown if obstacles did not exist), the mover's current
position/velocity, its dynamic limits, and an `ObstacleLayout`, and
returns whether that base command is predicted to collide with an
obstacle under the SAME constrained point-mass dynamics used by
`SoldierEnv` -- and, if so, a deterministic bypass direction to fly
instead.

Design goals (see the Phase-3B specification):
  - analytical / interpretable / deterministic given state + RNG realization
  - lightweight, local (no global planning, no search, no RL)
  - reuses the existing `advance_velocity` constrained-dynamics primitive
    for prediction, so the predictor's model of "how the mover actually
    moves" cannot drift out of sync with the real simulation
  - never mutates environment state during prediction (copies/locals only)
  - consumes ZERO randomness

Intended reuse: `SoldierEnv` uses this for the hostile UAV; the SAME
primitives (predict_constrained_trajectory / predict_collision /
generate_bypass_candidates / evaluate_and_select_candidate) are meant to be
reusable later for obstacle-aware Lead / RMPC candidate checking, or a
second `ObstaclePlanner` instance for another mover. Nothing here is
specific to any one policy or to stochastic hostile motion.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

from uav_defend.dynamics.constrained_point_mass import advance_velocity, apply_boundary
from uav_defend.obstacles.geometry import AABBObstacle
from uav_defend.obstacles.layout import ObstacleLayout

# Fixed, deterministic candidate order -- also the final tie-break in
# `evaluate_and_select_candidate`.
_CANDIDATE_MODES = ("left", "right", "climb")


@dataclass(frozen=True)
class DynamicsLimits:
    """Bundles the constrained-dynamics AND domain-boundary parameters
    needed to predict a trajectory identically to `SoldierEnv._advance_velocity`
    / `SoldierEnv._apply_boundary`. Omitting the boundary clip during
    prediction would let a descending/ascending mover's predicted z (or
    x/y) escape past the real ground/ceiling/wall limits -- something the
    real simulation never allows -- and spuriously miss an obstacle the
    real (clipped) trajectory would actually collide with."""

    max_speed: float
    max_accel: float
    max_turn_rate_rad: float
    max_climb_rate: float
    max_descent_rate: float
    dt: float
    eps: float
    L: float
    max_altitude: float


@dataclass(frozen=True)
class CollisionPrediction:
    """Result of `predict_collision()`."""

    collision: bool
    obstacle_index: int | None = None
    step_index: int | None = None
    min_clearance: float = float("inf")


@dataclass(frozen=True)
class BypassCandidate:
    """One deterministic candidate direction generated by
    `generate_bypass_candidates()`."""

    mode: str
    direction: np.ndarray
    waypoint: np.ndarray


@dataclass(frozen=True)
class CandidateEvaluation:
    """One candidate after simulation, ready for lexicographic selection.

    `meets_clearance` records whether `min_clearance` satisfies the
    configured `enemy_obstacle_clearance` requirement -- clearance is a
    safety REQUIREMENT (see `evaluate_and_select_candidate`), not a
    quantity to be maximized without limit."""

    mode: str
    direction: np.ndarray
    waypoint: np.ndarray
    collision: bool
    min_clearance: float
    meets_clearance: bool
    progress: float
    angular_deviation: float
    order_index: int


def _unit(vector: np.ndarray, fallback: np.ndarray, eps: float) -> np.ndarray:
    norm = float(np.linalg.norm(vector))
    if norm > eps:
        return vector / norm
    return fallback


def predict_constrained_trajectory(
    position: np.ndarray,
    velocity: np.ndarray,
    direction: np.ndarray,
    limits: DynamicsLimits,
    horizon_steps: int,
) -> tuple[list[np.ndarray], list[np.ndarray]]:
    """Simulate `horizon_steps` steps of the SAME constrained point-mass
    dynamics used by `SoldierEnv`, commanding a FIXED unit `direction`
    (desired_velocity = limits.max_speed * direction) every step.

    Pure: does not mutate `position`/`velocity`, does not touch any
    environment/RNG state. Returns (positions, velocities), each a list of
    length `horizon_steps + 1` (index 0 is the starting state).
    """
    if horizon_steps < 1:
        raise ValueError(f"horizon_steps must be >= 1, got {horizon_steps}")

    p = np.array(position, dtype=np.float64, copy=True)
    v = np.array(velocity, dtype=np.float64, copy=True)
    desired_velocity = limits.max_speed * np.asarray(direction, dtype=np.float64)

    positions = [p.copy()]
    velocities = [v.copy()]
    for _ in range(horizon_steps):
        v, _diag = advance_velocity(
            current_velocity=v,
            desired_velocity=desired_velocity,
            max_speed=limits.max_speed,
            max_accel=limits.max_accel,
            max_turn_rate_rad=limits.max_turn_rate_rad,
            max_climb_rate=limits.max_climb_rate,
            max_descent_rate=limits.max_descent_rate,
            dt=limits.dt,
            eps=limits.eps,
        )
        v = np.asarray(v, dtype=np.float64)
        p = p + v * limits.dt
        p, v = apply_boundary(p, v, L=limits.L, max_altitude=limits.max_altitude)
        positions.append(p.copy())
        velocities.append(v.copy())
    return positions, velocities


def predict_collision(positions: list[np.ndarray], layout: ObstacleLayout) -> CollisionPrediction:
    """Swept-collision-check every consecutive predicted segment, in
    time order, against `layout`. Returns the FIRST (earliest-step)
    collision found, plus the minimum point-wise clearance observed across
    every predicted waypoint (a useful diagnostic/tie-break even when no
    collision occurs)."""
    min_clearance = float("inf")
    for p in positions:
        min_clearance = min(min_clearance, layout.min_clearance(p))

    for step_index in range(len(positions) - 1):
        result = layout.first_segment_intersection(positions[step_index], positions[step_index + 1])
        if result.intersects:
            return CollisionPrediction(
                collision=True,
                obstacle_index=result.obstacle_index,
                step_index=step_index,
                min_clearance=min_clearance,
            )
    return CollisionPrediction(collision=False, min_clearance=min_clearance)


def _direction_to(position: np.ndarray, target: np.ndarray, fallback: np.ndarray, eps: float) -> np.ndarray:
    return _unit(np.asarray(target, dtype=np.float64) - np.asarray(position, dtype=np.float64), fallback, eps)


def _lateral_axis(u_base: np.ndarray, eps: float) -> np.ndarray:
    """Horizontal unit vector perpendicular to `u_base`'s horizontal
    projection (90 deg CCW), with a fixed fallback for a (near-)vertical
    `u_base`."""
    raw = np.array([-u_base[1], u_base[0]], dtype=np.float64)
    return _unit(raw, np.array([1.0, 0.0]), eps)


def _inflated_footprint_xy(obstacle: AABBObstacle, clearance: float) -> tuple[float, float, float, float]:
    """The obstacle's horizontal (x, y) AABB footprint inflated by
    `clearance` on every side -- a NAVIGATION/reasoning device only (the
    physical `AABBObstacle` itself is never modified). Returns
    (xmin, xmax, ymin, ymax)."""
    return (
        float(obstacle.min_corner[0] - clearance), float(obstacle.max_corner[0] + clearance),
        float(obstacle.min_corner[1] - clearance), float(obstacle.max_corner[1] + clearance),
    )


def _segment_clips_rectangle_xy(
    p0_xy: np.ndarray, p1_xy: np.ndarray, xmin: float, xmax: float, ymin: float, ymax: float, tol: float,
) -> bool:
    """True iff the straight segment `p0_xy` -> `p1_xy` enters the STRICT
    interior of the axis-aligned rectangle at some point strictly before
    reaching `p1_xy` (2-D slab method). Merely touching the boundary
    exactly at the destination `p1_xy` itself (e.g. arriving at one of the
    rectangle's own corners) does NOT count as "clipping" -- only genuine
    entry before that point does."""
    p0 = np.asarray(p0_xy, dtype=np.float64)
    p1 = np.asarray(p1_xy, dtype=np.float64)
    direction = p1 - p0
    bounds = ((xmin, xmax), (ymin, ymax))
    t_min, t_max = 0.0, 1.0
    for axis in range(2):
        lo, hi = bounds[axis]
        if abs(direction[axis]) < tol:
            if p0[axis] < lo - tol or p0[axis] > hi + tol:
                return False  # parallel to this axis and outside the slab: never intersects
            continue
        t1 = (lo - p0[axis]) / direction[axis]
        t2 = (hi - p0[axis]) / direction[axis]
        if t1 > t2:
            t1, t2 = t2, t1
        t_min = max(t_min, t1)
        t_max = min(t_max, t2)
        if t_min > t_max + tol:
            return False
    return t_min < 1.0 - tol


def _corner_side(u_h_unit: np.ndarray, p_xy: np.ndarray, corner_xy: np.ndarray, eps: float) -> str | None:
    """Classify `corner_xy` as "left" or "right" of the approach direction
    `u_h_unit`, using the sign of the 2-D cross product
    cross(u_base_xy, corner_xy - p_xy). None for the (rare, near-degenerate)
    case where the corner lies almost exactly along the approach axis."""
    to_corner = corner_xy - p_xy
    cross = u_h_unit[0] * to_corner[1] - u_h_unit[1] * to_corner[0]
    if cross > eps:
        return "left"
    if cross < -eps:
        return "right"
    return None


def _visible_corner_waypoint(
    position: np.ndarray, obstacle: AABBObstacle, u_base: np.ndarray, clearance: float, mode: str, eps: float,
) -> np.ndarray | None:
    """Geometry-aware horizontal bypass target: the nearest corner of the
    clearance-inflated obstacle footprint that is (a) on the requested
    `mode` ("left"/"right") side of the approach direction `u_base`, and
    (b) directly reachable in a straight line from the mover's current
    horizontal position WITHOUT the path itself clipping the inflated
    footprint first (a corner can individually have full clearance while
    the straight approach path to it still cuts through the margin --
    this is exactly the defect this function fixes; see the Phase-3D
    report). Returns None if no such corner exists (falls back to the
    center-offset formula -- see `_horizontal_bypass_candidate`)."""
    xmin, xmax, ymin, ymax = _inflated_footprint_xy(obstacle, clearance)
    corners = (
        np.array([xmin, ymin]), np.array([xmax, ymin]),
        np.array([xmax, ymax]), np.array([xmin, ymax]),
    )
    p_xy = np.asarray(position[:2], dtype=np.float64)
    u_h_unit = _unit(np.asarray(u_base[:2], dtype=np.float64), np.array([1.0, 0.0]), eps)

    reachable = []
    for corner in corners:
        if _corner_side(u_h_unit, p_xy, corner, eps) != mode:
            continue
        if _segment_clips_rectangle_xy(p_xy, corner, xmin, xmax, ymin, ymax, tol=eps):
            continue  # this corner is occluded: a straight line to it clips the box first
        reachable.append(corner)

    if not reachable:
        return None
    # Deterministic tie-break for the (rare) case of multiple reachable
    # corners on the same side: nearest first.
    reachable.sort(key=lambda c: float(np.linalg.norm(c - p_xy)))
    return reachable[0]


def _horizontal_bypass_candidate(
    position: np.ndarray, obstacle: AABBObstacle, u_base: np.ndarray, clearance: float, mode: str, eps: float,
) -> BypassCandidate:
    """Geometry-aware tangent-corner horizontal bypass target (Phase 3D):
    a visible corner of the clearance-inflated footprint on the requested
    side, reachable without the straight approach path itself clipping the
    inflated margin. Falls back to the Phase-3C center-offset formula only
    in the rare degenerate case where no corner qualifies (e.g. the mover
    is already essentially on top of the obstacle)."""
    target_xy = _visible_corner_waypoint(position, obstacle, u_base, clearance, mode, eps)
    if target_xy is None:
        lateral = _lateral_axis(u_base, eps)
        sign = 1.0 if mode == "left" else -1.0
        lateral_extent = (
            abs(lateral[0]) * obstacle.half_extents[0] + abs(lateral[1]) * obstacle.half_extents[1] + clearance
        )
        target_xy = obstacle.center[:2] + sign * lateral * lateral_extent
    waypoint = np.array([target_xy[0], target_xy[1], position[2]], dtype=np.float64)
    direction = _direction_to(position, waypoint, fallback=u_base, eps=eps)
    return BypassCandidate(mode=mode, direction=direction, waypoint=waypoint)


def _climb_bypass_candidate(
    position: np.ndarray, obstacle: AABBObstacle, u_base: np.ndarray, clearance: float, max_altitude: float, eps: float,
) -> BypassCandidate | None:
    """Target directly above the MOVER'S OWN current position (not the
    obstacle's center): a near-vertical ascent that never enters the
    obstacle's horizontal footprint while still below its top, avoiding a
    climb-rate-vs-horizontal-speed mismatch that could otherwise clip the
    obstacle mid-ascent on a long diagonal approach."""
    target_z = float(obstacle.max_corner[2]) + clearance
    if target_z > max_altitude + eps:
        return None  # climbing high enough to clear is infeasible: omit the candidate
    waypoint = np.array([position[0], position[1], target_z], dtype=np.float64)
    direction = _direction_to(position, waypoint, fallback=u_base, eps=eps)
    return BypassCandidate(mode="climb", direction=direction, waypoint=waypoint)


def generate_bypass_candidates(
    position: np.ndarray,
    obstacle: AABBObstacle,
    u_base: np.ndarray,
    clearance: float,
    max_altitude: float,
    eps: float = 1e-8,
) -> list[BypassCandidate]:
    """Deterministic candidate set for bypassing `obstacle`: horizontal
    left, horizontal right, and (if geometrically feasible) climb-above.
    Targets are based on the obstacle's actual AABB, inflated by
    `clearance` so candidates do not skim the exact boundary. NO
    randomness; candidate order is always left, right, climb."""
    candidates = [
        _horizontal_bypass_candidate(position, obstacle, u_base, clearance, "left", eps),
        _horizontal_bypass_candidate(position, obstacle, u_base, clearance, "right", eps),
    ]
    climb = _climb_bypass_candidate(position, obstacle, u_base, clearance, max_altitude, eps)
    if climb is not None:
        candidates.append(climb)
    return candidates


# Candidate safety categories used by `candidate_category`/`candidate_sort_key`.
CATEGORY_SAFE = 0                    # collision-free AND meets_clearance
CATEGORY_MARGIN_DEFICIENT = 1        # collision-free BUT below required_clearance
CATEGORY_COLLIDING = 2


def candidate_category(evaluation: CandidateEvaluation) -> int:
    """Classify one evaluated candidate into CATEGORY_SAFE /
    CATEGORY_MARGIN_DEFICIENT / CATEGORY_COLLIDING (see
    `evaluate_and_select_candidate`'s docstring for the full rule)."""
    if evaluation.collision:
        return CATEGORY_COLLIDING
    return CATEGORY_SAFE if evaluation.meets_clearance else CATEGORY_MARGIN_DEFICIENT


def candidate_sort_key(evaluation: CandidateEvaluation):
    """Lexicographic sort key implementing the category-dependent ranking
    (category is always the primary key; `min()` over this key picks the
    best candidate -- see `evaluate_and_select_candidate`)."""
    category = candidate_category(evaluation)
    if category == CATEGORY_SAFE:
        return (category, -evaluation.progress, evaluation.angular_deviation, -evaluation.min_clearance, evaluation.order_index)
    if category == CATEGORY_MARGIN_DEFICIENT:
        return (category, -evaluation.min_clearance, -evaluation.progress, evaluation.angular_deviation, evaluation.order_index)
    return (category, -evaluation.min_clearance, evaluation.order_index)  # CATEGORY_COLLIDING


def evaluate_and_select_candidate(
    position: np.ndarray,
    velocity: np.ndarray,
    u_base: np.ndarray,
    candidates: list[BypassCandidate],
    layout: ObstacleLayout,
    target_position: np.ndarray,
    limits: DynamicsLimits,
    horizon_steps: int,
    required_clearance: float,
) -> tuple[CandidateEvaluation, bool]:
    """Simulate every candidate with the real constrained dynamics and pick
    one via a LEXICOGRAPHIC rule (no tuned weights, no scoring function).

    Clearance is treated as a safety REQUIREMENT, not a quantity to
    maximize without limit (an unconstrained "maximize clearance" rule
    tends to always prefer a straight-up climb, since climbing away from
    the obstacle's footprint typically yields the largest raw clearance --
    safe, but unnecessarily conservative for mission progress). Every
    candidate is classified into one of three categories
    (`candidate_category`):

        A. SAFE: collision-free AND min_clearance >= required_clearance
        B. COLLISION-FREE BUT MARGIN-DEFICIENT: collision-free AND
           min_clearance < required_clearance
        C. COLLIDING

    Selection (`candidate_sort_key`, category always primary):

        - If any SAFE candidates exist, choose among them by:
            1. greatest progress toward `target_position`
            2. smaller angular deviation from `u_base`
            3. larger minimum clearance
            4. fixed candidate order (left, right, climb) as final tie-break
        - Else if any collision-free (margin-deficient) candidates exist,
          choose among them by:
            1. larger minimum clearance
            2. greatest progress
            3. smaller angular deviation
            4. fixed order
        - Else (every candidate collides), choose the candidate with
          maximum predicted clearance; `fallback_used` is True.

    Returns (best_evaluation, fallback_used) -- `fallback_used` is True
    iff even the best candidate is still predicted to collide (i.e. no
    candidate was collision-free)."""
    if not candidates:
        raise ValueError("candidates must be non-empty")

    start_dist = float(np.linalg.norm(np.asarray(position, dtype=np.float64) - np.asarray(target_position, dtype=np.float64)))
    evaluations: list[CandidateEvaluation] = []
    for order_index, candidate in enumerate(candidates):
        positions, _velocities = predict_constrained_trajectory(position, velocity, candidate.direction, limits, horizon_steps)
        prediction = predict_collision(positions, layout)
        end_dist = float(np.linalg.norm(positions[-1] - np.asarray(target_position, dtype=np.float64)))
        progress = start_dist - end_dist
        cos_angle = float(np.clip(np.dot(candidate.direction, u_base), -1.0, 1.0))
        angular_deviation = float(np.arccos(cos_angle))
        evaluations.append(CandidateEvaluation(
            mode=candidate.mode,
            direction=candidate.direction,
            waypoint=candidate.waypoint,
            collision=prediction.collision,
            min_clearance=prediction.min_clearance,
            meets_clearance=(not prediction.collision) and prediction.min_clearance >= required_clearance,
            progress=progress,
            angular_deviation=angular_deviation,
            order_index=order_index,
        ))

    best = min(evaluations, key=candidate_sort_key)
    return best, best.collision


@dataclass
class ObstacleAvoidancePlanner:
    """Stateful wrapper adding avoidance persistence/hysteresis on top of
    the stateless prediction/candidate-selection primitives above.

    Persistence anchors on a fixed WORLD-FRAME WAYPOINT chosen at
    activation/reselection time, not on a direction re-derived from
    `u_base` every step: `u_base` itself wobbles step-to-step (weave/
    heading-noise/evasion), so re-deriving "left of u_base" each step
    would make the followed path drift with that noise. Flying toward a
    fixed waypoint instead gives a stable, non-oscillating bypass path,
    while still re-checking feasibility every step and reselecting a new
    waypoint if the current one becomes infeasible (Step 7).

    Consumes ZERO randomness. One instance tracks avoidance state for ONE
    mover (e.g. the hostile UAV); a defender-side user of this module
    would own a separate instance.
    """

    clearance: float
    horizon_steps: int
    release_steps: int
    max_altitude: float
    eps: float = 1e-8

    active: bool = field(default=False, init=False)
    obstacle_index: int | None = field(default=None, init=False)
    mode: str | None = field(default=None, init=False)
    waypoint: np.ndarray | None = field(default=None, init=False)
    _clear_streak: int = field(default=0, init=False)

    def reset(self) -> None:
        """Clear all persistence state (call on episode reset)."""
        self.active = False
        self.obstacle_index = None
        self.mode = None
        self.waypoint = None
        self._clear_streak = 0

    def plan(
        self,
        position: np.ndarray,
        velocity: np.ndarray,
        u_base: np.ndarray,
        layout: ObstacleLayout,
        target_position: np.ndarray,
        limits: DynamicsLimits,
    ) -> dict:
        """Compute this step's commanded direction.

        Returns a dict with keys: "direction" (np.ndarray, unit vector to
        command instead of/as `u_base`), "active" (bool),
        "mode" (str | None), "obstacle_index" (int | None),
        "predicted_collision_step" (int | None),
        "predicted_min_clearance" (float), "fallback_used" (bool).
        """
        u_base = np.asarray(u_base, dtype=np.float64)

        if len(layout) == 0:
            self.reset()
            return self._result(direction=u_base, predicted=CollisionPrediction(collision=False), fallback_used=False)

        base_positions, _ = predict_constrained_trajectory(position, velocity, u_base, limits, self.horizon_steps)
        base_prediction = predict_collision(base_positions, layout)

        if not self.active:
            if not base_prediction.collision:
                return self._result(direction=u_base, predicted=base_prediction, fallback_used=False)
            return self._activate(position, velocity, u_base, layout, target_position, limits, base_prediction)

        # Currently active: condition B (persistence) applies. Release
        # requires BOTH the base command to be predicted collision-free
        # AND actual current clearance from the persisted obstacle to be
        # comfortably beyond `clearance` -- momentary noise in u_base's
        # heading can make the SHORT-horizon prediction look clear even
        # while still immediately adjacent to the obstacle, and residual
        # velocity built up while following a bypass waypoint can carry
        # the mover an additional max_speed*dt before it can react again,
        # so that one-step worst-case travel distance is required as
        # extra release margin (a physically-motivated, deterministic
        # quantity -- not a tuned gain).
        release_clearance = self.clearance + limits.max_speed * limits.dt
        actual_clearance = layout[self.obstacle_index].clearance_to_point(position)
        if not base_prediction.collision and actual_clearance >= release_clearance:
            self._clear_streak += 1
            if self._clear_streak >= self.release_steps:
                self.reset()
                return self._result(direction=u_base, predicted=base_prediction, fallback_used=False)
        else:
            self._clear_streak = 0

        # Feasibility of the PERSISTED waypoint -- direction is re-derived
        # from the CURRENT position toward the SAME fixed waypoint (not
        # recomputed from the noisy u_base), so the followed path is
        # stable. Independent of whether base_prediction currently names
        # an obstacle, so a momentarily obstacle-free base prediction can
        # never leave obstacle_index/waypoint undefined here.
        current_direction = _direction_to(position, self.waypoint, fallback=u_base, eps=self.eps)
        positions, _ = predict_constrained_trajectory(position, velocity, current_direction, limits, self.horizon_steps)
        current_feasible = not predict_collision(positions, layout).collision

        if current_feasible:
            return self._result(direction=current_direction, predicted=base_prediction, fallback_used=False)

        # Current waypoint became infeasible: reselect among a fresh
        # candidate set for the SAME persisted obstacle.
        obstacle = layout[self.obstacle_index]
        candidates = generate_bypass_candidates(position, obstacle, u_base, self.clearance, self.max_altitude, self.eps)
        best, fallback_used = evaluate_and_select_candidate(
            position, velocity, u_base, candidates, layout, target_position, limits, self.horizon_steps, self.clearance,
        )
        self.mode = best.mode
        self.waypoint = best.waypoint
        self._clear_streak = 0
        return self._result(direction=best.direction, predicted=base_prediction, fallback_used=fallback_used)

    def _activate(self, position, velocity, u_base, layout, target_position, limits, base_prediction) -> dict:
        obstacle = layout[base_prediction.obstacle_index]
        candidates = generate_bypass_candidates(position, obstacle, u_base, self.clearance, self.max_altitude, self.eps)
        best, fallback_used = evaluate_and_select_candidate(
            position, velocity, u_base, candidates, layout, target_position, limits, self.horizon_steps, self.clearance,
        )
        self.active = True
        self.obstacle_index = base_prediction.obstacle_index
        self.mode = best.mode
        self.waypoint = best.waypoint
        self._clear_streak = 0
        return self._result(direction=best.direction, predicted=base_prediction, fallback_used=fallback_used)

    def _result(self, direction: np.ndarray, predicted: CollisionPrediction, fallback_used: bool) -> dict:
        return {
            "direction": np.asarray(direction, dtype=np.float64),
            "active": self.active,
            "mode": self.mode,
            "obstacle_index": self.obstacle_index,
            "predicted_collision_step": predicted.step_index,
            "predicted_min_clearance": predicted.min_clearance,
            "fallback_used": fallback_used,
        }
